language: python
python:
  - "3.6-dev"
  - "3.7"
  - "3.7-dev"
  - "3.8"
  - "3.8-dev"
os: linux
before_install:
  - sudo apt-get install libsqlite3-mod-spatialite
  - sudo apt-get install -y libspatialite-dev
  - sudo apt-get autoremove

install:
  - pip install -r requirements.txt
  - pip install pytest pytest-cov codecov cython pycodestyle

script:
  - cd aequilibrae/paths
  - python setup_Assignment.py build_ext --inplace
  - cd ..
  - cd ..
  - python -m pytest
#after_success:
#- codecov