assignment:
  Equilibrium:
    rgap: 1.0e-03
distribution:
  gravity:
    max error: 0.0001
    max iterations: 100
    max trip length: -1
  ipf:
    balancing tolerance: 0.001
    convergence level: 0.0001
    max iterations: 5000
system:
  cpus: 8
  default_directory: C:\Users\pedro.camargo\Documents\sourcecode\drt
  driving side: right
  logging: true
  report zeros: 1
  temp directory: /temp
  spatialite_path: C:\Users\pedro\Documents\mod_spatialite-NG-win-amd64
network:
  links:
    fields:
      one-way:
        - link_id:
            description: link_id
            type: integer
        - a_node:
            description: a_node
            type: integer
        - b_node:
            description: b_node
            type: integer
        - direction:
            description: direction
            type: integer
        - length:
            description: length
            type: numeric
        - name:
            description: name
            type: varchar
        - link_type:
            description: link_type
            type: varchar
      two-way:
        - lanes:
            description: lanes
            type: integer
        - capacity:
            description: capacity
            type: numeric
        - speed:
            description: speed
            type: numeric
  nodes:
    fields:
      - node_id:
          description: node_id
          type: integer
      - is_centroid:
          description: is_centroid
          type: integer