name: Upload Linux Python Package

on: [pull_request]
#on:
#  release:
#    types: [prereleased, published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install twine
    - name: Build manylinux Python wheels
      uses: RalfG/python-wheels-manylinux-build@v0.1
      with:
        python-versions: 'cp36-cp36m cp37-cp37m cp38-cp38'
        build-requirements: 'setuptools numpy cython'
#    - name: Publish wheels to PyPI
#      env:
#        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
#        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
#      run: |
#        twine upload wheelhouse/*-manylinux1_x86_64.whl

    - name: Upload to site
      uses: SamKirkland/FTP-Deploy-Action@2.0.0
      env:
        FTP_SERVER: ${{ secrets.DOC_FTP_SERVER }}
        FTP_USERNAME: ${{ secrets.DOC_FTP_USER }}
        FTP_PASSWORD: ${{ secrets.DOC_FTP_PASSWORD }}
        LOCAL_DIR: wheelhouse/
        REMOTE_DIR: wheels/
        ARGS: --transfer-all
