name: newTests

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.6, 3.7, 3.8]
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python-version }}
      uses: fylein/python-pytest-github-action@v1
      with:
        python-version: ${{ matrix.python-version }}
        args: pip3 install -r requirements.txt && flake8 && python aequilibrae/paths/setup_Assignment.py build_ext --inplace && pytest

