name: Tests

on: [pull_request]

jobs:
  build:
    runs-on: linux-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [docker://python:3.6, docker://python:3.7]
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python-version }}
      uses: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Lint with flake8
      run: |
        pip install flake8
        flake8
    - name: Test with pytest
      run: |
        cd aequilibrae/paths
        python setup_Assignment.py build_ext --inplace
        cd ..
        cd ..
        pip install pytest
        pytest
