name: TestsDocker

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      uses: docker://python:3.7
      - name: Install dependencies
        run: |
          ls
          pip install -r requirements.txt
      #          python -m pip install --upgrade pip
      - name: Lint with flake8
        run: |
          pip install flake8
          flake8
      - name: Test with pytest
        run: |
          apt-get install -y libspatialite-dev
          cd aequilibrae/paths
          python setup_Assignment.py build_ext --inplace
          cd ..
          cd ..
          pip install pytest
          pytest
