name: Tests

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.6, 3.7]
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
    - name: Set up Python ${{ matrix.python-version }}
      uses: dschep/install-pipenv-action@v1
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        pipenv install -r requirements.txt
    - name: Lint with flake8
      run: |
        pipenv install flake8
        pipenv flake8
    - name: Test with pytest
      run: |
        cd aequilibrae/paths
        pipenv -m python setup_Assignment.py build_ext --inplace
        cd ..
        cd ..
        pipenv install pytest
        pipenv run python -m pytest
