name: Tests

on: [pull_request]

jobs:
  testing:
    runs-on: ubuntu-latest
#    strategy:
#      max-parallel: 4
#      matrix:
#        docker-version: [docker://python:3.6, docker://python:3.7, docker://python:3.8]
#        ${{ matrix.python-version }}
    steps:
    - uses: docker://python:3.7
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: |
        sudo apt-get update
        pip3 install setuptools --upgrade
        sudo apt-get install python3-pyqt5
        pip3 install numpy
        pip3 install pyaml
        pip3 install cython
        pip3 install openmatrix
        pip3 install pyshp
        pip3 install requests
        pip3 install pytest
        sudo apt-get install libsqlite3-mod-spatialite
        sudo apt-get install -y libspatialite-dev
        sudo apt-get autoremove

    - name: Compile library
      run: |
        cd aequilibrae/paths
        python3 setup_Assignment.py build_ext --inplace
        cd ..
        cd ..

#    - name: Lint with flake8
#      run: |
#        flake8

    - name: Test with pytest
      run: |
        python3 -m pytest
