name: Tests

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.6, 3.7, 3.8]
    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: |
        pipenv install --python ${{ matrix.python-version }}
        pipenv install -r requirements.txt
        pipenv install flake8
    - name: Lint with flake8
      run: |
        pipenv run flake8
    - name: Test with pytest
      run: |
        cd aequilibrae/paths
        python setup_Assignment.py build_ext --inplace
        cd ..
        cd ..
        pipenv install pytest
        pipenv run python -m pytest --cov-report term-missing --cov=auction
